/**
* (c) Christian Schlosrich 2012
* A timer build on requestAnimationFrame. Timer will pause when rAF stops firing and resume when rAF resumes.
* Timer can either be based on miliseconds or frames
* Useful for linking game timers to animation based of rAF.
* 
* @param {Number} duration in miliseconds or number of frames if useFrames is set to true
* @param {Function} notify callback
* @param {Boolean} useFrames false (default) makes the timer use miliseconds. True forces it to frame based timing.
*/
fx.RAFTimer = function(duration, notify, useFrames){

    /**
    * Validating args
    */
    if(!window.requestAnimationFrame || !window.cancelAnimationFrame){
        throw new Error('requestAnimationFrame and cancelAnimationFrame are required for RAFTimer.');
    } else if(!duration){
        throw new Error('Missing required parameter \'duration\'.');
    } else if(isNaN(duration)){
        throw new Error('Parameter \'duration\' is not a Number.');
    } else if(!notify){
        throw new Error('Missing required parameter \'notify\'.');
    }

	this.usePresicionTimer = !!window.performance && !!window.performance.now;

	/**
	* High precision timer
	* http://updates.html5rocks.com/2012/08/When-milliseconds-are-not-enough-performance-now
	*/
	window.performance = window.performance || {};
	performance.now = (function() {
		return performance.now    ||
			performance.mozNow    ||
			performance.msNow     ||
			performance.oNow      ||
			performance.webkitNow ||
			function() { return new Date().getTime(); };
	})();

    this.duration = duration;
    this.notify = notify;
    this.useFrames = useFrames || false;

    // The current request ID as generated by a call to requestAnimationFrame
    this.requestId = 0;

    this.running = false;
    this.paused = false;
    this.ms = Infinity;
    this.currentTime = 0;
    this.currentFrame = 0;

    // Increased by one when timer reaches it's duration and notify is called
    this.count = 0;

    /**
    * Max delta time threshold set at 160 ms / 6.25 fps. 
    * When frame rate drops this low we can safely assume that requestAnimationFrame has stopped firing and thus we stop accumulating time (only other viable explanation is that the user's computer is crap and can't produce a proper frame rate)
    */
    this.maxDeltaTime = 160;

    var lastTime,
    	self = this;

    this._callback = function(){
        self.currentTime = self.duration;
        self.count++;
        self.lastTime = 0;
        self.reset();
      	self.notify.call(self);
    }

    this._tick = function(){
    	if(!self.running || self.paused) return;

        if(self.useFrames){
            if(self.currentFrame == self.duration) self._callback();
        } else if(self.currentTime >= self.duration){
            self._callback();
        }

    	var now = performance.now();
		self.ms = now - (lastTime || now);

        // When rAF resumes from idle state and ms is greater than 160 ms don't add the value to accumulated time (assuming the tab / window was inactive)
		if(self.ms > self.maxDeltaTime) self.ms = 0;
		lastTime = now;

        self.currentTime += self.ms;
        self.currentFrame++;
        self.requestId = requestAnimationFrame(self._tick);
    }
}

fx.RAFTimer.prototype = {

    /**
    * Starts the timer (if timer is paused only resume can re-start the timer)
    */
    start : function(){
    	if(this.running || this.paused) return;
    	this.running = true;
    	this.requestId = requestAnimationFrame(this._tick);
    },

    /**
    * Stops the timer (timer will not resume if rAF stops and is restarted)
    */
    stop : function(){
    	if(!this.running) return;
    	this.running = false;
        this.paused = false;
        this.reset();
    	cancelAnimationFrame(this.requestId);
    },

    /**
    * Pauses the timer (if the timer is already running)
    */
    pause : function(){
        if(this.paused || !this.running) return;
        this.paused = true;
    },

    /**
    * Resumes from the last current time if timer is running but paused (opposed to stop that triggers a restart once rAF continues)
    */
    resume : function(){
        if(!this.paused) return;
        this.paused = false;
        this.requestId = requestAnimationFrame(this._tick);
    },

    /**
    * Returns the current time as properly formatted seconds and miliseconds (human readable).
    */
    getFormattedTime : function(){
		return (this.currentTime / 1000).toFixed(2);
    },

    /**
    * Sets the current running time to 0
    */
    reset : function(){
    	this.currentTime = 0;
        this.currentFrame = 0;
    },

    /**
    * Returns true if rAF is active (currenly intervals exceeding 160ms will result in false)
    */
    rafActive : function(){
        return this.ms < this.maxDeltaTime;
    },

    /**
    * Destroys the timer and remove internal references for GC.
    */
    destroy : function(){
        this.stop();
        this.notify = null;
        this.duration = null;
    },

    /**
    * Returns a String representation of fx.RAFTimer
    */
    toString : function(){
        var res = '[RAFTimer] ';

        if(this.useFrames){
            res += 'duration(frames): ' + this.duration + ', currentFrame: ' + this.currentFrame;
        } else{
            res += 'duration(ms): ' + this.duration + ', currentTime: ' + this.getFormattedTime();
        }

        res += ', count: ' + this.count + ', running: ' + this.running + ', paused: ' + this.paused;

		// Precisicion timer is not applicaple when using frame based timing since time stamps are not used
        if(!this.useFrames){
            res += ', precisionTimer: ' + this.usePresicionTimer;
        }

        return res;
    }
}

=